name: Build APK
on: [push, workflow_dispatch]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Strip BOM from all files
        run: find . -type f -name "*.gradle" -o -name "*.java" -o -name "*.xml" | xargs sed -i '1s/^\xef\xbb\xbf//'
      
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      # МЕНЯЕМ assembleRelease на assembleDebug
      - name: Build with Gradle
        run: ./gradlew assembleDebug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-iptv-app
          # МЕНЯЕМ путь к файлу на debug
          path: app/build/outputs/apk/debug/app-debug.apk
